package com.tzdr.domain.web.entity.future;


// Generated 2015-7-23 14:20:39 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.tzdr.common.domain.FbaseCrudEntity;
import com.tzdr.common.utils.Dates;
import com.tzdr.domain.cache.CacheManager;
import com.tzdr.domain.cache.DataDicKeyConstants;

/**
 * FCapitalInfo generated by hbm2java
 */
@Entity
@Table(name="f_capital_info")
public class FcapitalInfo extends FbaseCrudEntity   implements java.io.Serializable {
	

	//账户id
     //private String faid;
    @ManyToOne
    @JoinColumn(name="f_aid")
     private FaccountInfo  faccountInfo;
     //三方流水号
	 private String tripartiteFlow;
	 //交易明细号 【201507080000001】
	 private String tradeInfo;
	 //交易金额
	 private BigDecimal tradeMoney;
	 //账户余额
	 private BigDecimal balance;
	 //业务类型 1:交易费支出、2:交易费退还、3:止损金支出、4:止损金退还、5:操盘盈利、6:保证金支出、7:保证金退还、8:充值、9:提现、
	 //21：管理费、30：内转划入、31：内转划出、41：用户申报费(委托费),42利润分配
	 private Integer businessType;
	 
	 @Transient
	 private String businessTypeValue;
	 //存取放向【1.存、-1.取、0.冻结】
	 private Integer direction;
	 //状态【1.支付、-1.未支付】
     private Integer state;
     //备注
     private String remark;
     @Transient
     private String crartTimeValue;
     @Transient
     private Integer milliSecondValue;
    public FcapitalInfo() {
    }
    
    public FaccountInfo getFaccountInfo() {
		return faccountInfo;
	}

	public void setFaccountInfo(FaccountInfo faccountInfo) {
		this.faccountInfo = faccountInfo;
	}
    
    @Column(name="tripartite_flow", length=150)
    public String getTripartiteFlow() {
        return this.tripartiteFlow;
    }
    
    public void setTripartiteFlow(String tripartiteFlow) {
        this.tripartiteFlow = tripartiteFlow;
    }

    
    @Column(name="trade_info", length=18)
    public String getTradeInfo() {
        return this.tradeInfo;
    }
    
    public void setTradeInfo(String tradeInfo) {
        this.tradeInfo = tradeInfo;
    }

    
    @Column(name="trade_money")
    public BigDecimal getTradeMoney() {
        return this.tradeMoney;
    }
    
    public void setTradeMoney(BigDecimal tradeMoney) {
        this.tradeMoney = tradeMoney;
    }

    
    @Column(name="balance")
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    
    @Column(name="business_type")
    public Integer getBusinessType() {
        return this.businessType;
    }
    
    public void setBusinessType(Integer businessType) {
        this.businessType = businessType;
    }

    
    @Column(name="direction")
    public Integer getDirection() {
        return this.direction;
    }
    
    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    
    @Column(name="state")
    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }

    
    @Column(name="remark", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public String getBusinessTypeValue() {
		if(this.businessType!=null){
			this.businessTypeValue = CacheManager.getDataMapByKey(DataDicKeyConstants.FUND_TYPE, String.valueOf(this.businessType));
		}
		return businessTypeValue;
	}

	public void setBusinessTypeValue(String businessTypeValue) {
		this.businessTypeValue = businessTypeValue;
	}

	public String getCrartTimeValue() {
		if(this.getCreateTime()!=null){
			this.crartTimeValue = Dates.format(this.getCreateTime());
		}
		return crartTimeValue;
	}

	public void setCrartTimeValue(String crartTimeValue) {
		this.crartTimeValue = crartTimeValue;
	}

	public Integer getMilliSecondValue() {
		return milliSecondValue;
	}

	public void setMilliSecondValue(Integer milliSecondValue) {
		this.milliSecondValue = milliSecondValue;
	}

	


}


