package com.tzdr.domain.web.entity.future;


// Generated 2015-7-23 14:20:39 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.tzdr.common.domain.FbaseCrudEntity;

/**
 * FTradeParentAccount generated by hbm2java
 */
@Entity
@Table(name="f_trade_parent_account")
public class FtradeParentAccount extends FbaseCrudEntity implements java.io.Serializable {

	private static final long serialVersionUID = -3513424358404523098L;
	//账户编号
     private String accountNo;
     //期货公司
     private String facilitator;
     //账户名称
     private String name;
     //账户余额
     private BigDecimal balance;
     //密码
     private String password;
     //充值资金(资金总额)
     private BigDecimal prepaid;
     //资金余额
     private BigDecimal asset;
     //成交数
     private Integer tradeAmount;
     //优先级
     private String priority;
     //累计交易费
     private BigDecimal cumulativeTransaction;
     //利润分成
     private BigDecimal cumulativeProfit;
     //佣金
     private BigDecimal cumulativeCommission;
     //理论持仓限制
     private Integer theoryPosition;
     //实际持仓限制
     private Integer actualPosition;
     //会员号
     private String vipNo;
     //客户号
     private String customerNo;
     //行情地址
     private String maketAdd;
     //交易地址
     private String tradeAdd;
     //状态【1.启用中、-1.禁用中】
     private Integer state;

    public FtradeParentAccount() {
    }
    
    @Column(name="account_no", length=32)
    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    
    @Column(name="facilitator", length=90)
    public String getFacilitator() {
        return this.facilitator;
    }
    
    public void setFacilitator(String facilitator) {
        this.facilitator = facilitator;
    }

    
    @Column(name="name", length=90)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="balance")
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    
    @Column(name="password", length=459)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="prepaid")
    public BigDecimal getPrepaid() {
        return this.prepaid;
    }
    
    public void setPrepaid(BigDecimal prepaid) {
        this.prepaid = prepaid;
    }

    
    @Column(name="asset")
    public BigDecimal getAsset() {
        return this.asset;
    }
    
    public void setAsset(BigDecimal asset) {
        this.asset = asset;
    }

    
    @Column(name="trade_amount")
    public Integer getTradeAmount() {
        return this.tradeAmount;
    }
    
    public void setTradeAmount(Integer tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    
    @Column(name="priority", length=15)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    
    @Column(name="cumulative_transaction")
    public BigDecimal getCumulativeTransaction() {
        return this.cumulativeTransaction;
    }
    
    public void setCumulativeTransaction(BigDecimal cumulativeTransaction) {
        this.cumulativeTransaction = cumulativeTransaction;
    }

    
    @Column(name="cumulative_profit")
    public BigDecimal getCumulativeProfit() {
        return this.cumulativeProfit;
    }
    
    public void setCumulativeProfit(BigDecimal cumulativeProfit) {
        this.cumulativeProfit = cumulativeProfit;
    }

    
    @Column(name="cumulative_commission")
    public BigDecimal getCumulativeCommission() {
        return this.cumulativeCommission;
    }
    
    public void setCumulativeCommission(BigDecimal cumulativeCommission) {
        this.cumulativeCommission = cumulativeCommission;
    }

    
    @Column(name="theory_position")
    public Integer getTheoryPosition() {
        return this.theoryPosition;
    }
    
    public void setTheoryPosition(Integer theoryPosition) {
        this.theoryPosition = theoryPosition;
    }

    
    @Column(name="actual_position")
    public Integer getActualPosition() {
        return this.actualPosition;
    }
    
    public void setActualPosition(Integer actualPosition) {
        this.actualPosition = actualPosition;
    }

    
    @Column(name="vip_no", length=100)
    public String getVipNo() {
        return this.vipNo;
    }
    
    public void setVipNo(String vipNo) {
        this.vipNo = vipNo;
    }

    
    @Column(name="customer_no", length=100)
    public String getCustomerNo() {
        return this.customerNo;
    }
    
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
    }

    
    @Column(name="maket_add", length=500)
    public String getMaketAdd() {
        return this.maketAdd;
    }
    
    public void setMaketAdd(String maketAdd) {
        this.maketAdd = maketAdd;
    }

    
    @Column(name="trade_add", length=500)
    public String getTradeAdd() {
        return this.tradeAdd;
    }
    
    public void setTradeAdd(String tradeAdd) {
        this.tradeAdd = tradeAdd;
    }

    
    @Column(name="state")
    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }
}
